package fr.iutvannes.dual.model.importation
import fr.iutvannes.dual.model.dao.EleveDAO
import fr.iutvannes.dual.model.importation.readers.StudentReader
import fr.iutvannes.dual.model.persistence.Eleve
import java.io.InputStream


/**
 * Concise import report
 *
 * @param total: number of students in the file
 * @param created: number of students created
 * @param skipped: number of students skipped (duplicates)
 * @param errorCount: number of errors
 * @param errors: list of errors
 */
data class ImportReport(
    val total: Int,
    val created: Int,
    val skipped: Int,
    val errorCount: Int,
    val errors: List<String>
)


/**
 * Main logic of student import:
 * 1 - File type detection
 * 2 - Calling the appropriate reader
 * 3 - Data validation
 * 4 - Adding to the database
 *
 * @see Eleve
 * @see EleveDAO
 * @see StudentReader
 *
 * @param readers list of known readers
 * @param eleveDao DAO of students
 */
class ImportService(
    private val readers: List<StudentReader>,
    private val eleveDao: EleveDAO
) {

    /**
     * Importing a student file.
     *
     * @param input file stream (CSV/XLS)
     * @param fileName file name (for the extension)
     * @param mimeType MIME type if known (otherwise null)
     * @param classeNom class name if known (otherwise null)
     * @return import report
     */
    suspend fun import(
        input: InputStream,
        fileName: String,
        mimeType: String? = null,
        classeNom: String?
    ): ImportReport {

        val reader = pickReader(mimeType, fileName)
        val drafts = reader.read(input)

        // To avoid duplicates within the file itself
        val seen = mutableSetOf<Triple<String, String, String?>>()
        var created = 0
        var skipped = 0
        val errors = mutableListOf<String>()

        drafts.forEachIndexed { idx, d ->
            // +2 because index 0 = line 2 in the file = 1st student
            val rowNum = idx + 2

            // Minimum validation of first and last name
            if (d.firstName.isBlank()) {
                errors += "Ligne $rowNum : 'Prénom' vide"
                return@forEachIndexed
            }
            if (d.lastName.isBlank()) {
                errors += "Ligne $rowNum : 'Nom' vide"
                return@forEachIndexed
            }

            val effectiveClasse = when {
                !d.classe.isNullOrBlank() -> d.classe.trim()
                !classeNom.isNullOrBlank() -> classeNom.trim() // on prend la classe de l’écran
                else -> "Non renseignée"
            }

            // deduplication (removal of duplicates)
            val key = Triple(
                d.firstName.trim().lowercase(),
                d.lastName.trim().lowercase(),
                effectiveClasse.lowercase()
            )

            if (!seen.add(key)) {
                skipped++
                return@forEachIndexed
            }

            // Database deduplication (checks if the student already exists physically in the database)
            // This can be done cleanly by searching the list of students in the class
            val existants = eleveDao.getElevesByClasse(effectiveClasse)
            val estDejaEnBase = existants.any {
                it.prenom.equals(d.firstName.trim(), ignoreCase = true) &&
                        it.nom.equals(d.lastName.trim(), ignoreCase = true)
            }

            if (estDejaEnBase) {
                skipped++
                return@forEachIndexed
            }

          // creation Room entity
            val eleve = Eleve(
                id_eleve = 0, // ID generated by room
                prenom = d.firstName.trim(),
                nom = d.lastName.trim(),
                genre = d.genre, // We're getting the genre back
                classe = effectiveClasse
            )

            try {
                eleveDao.insert(eleve)
                created++
            } catch (e: Exception) {
                errors += "Ligne $rowNum : erreur de persistance (${e::class.simpleName})"
            }
        }

        return ImportReport(
            total = drafts.size,
            created = created,
            skipped = skipped,
            errorCount = errors.size,
            errors = errors
        )
    }

    /**
     * Chooses the first reader that supports the file.
     *
     * @param mimeType MIME type of the file
     * @param fileName filename
     * @return corresponding reader
     */
    private fun pickReader(mimeType: String?, fileName: String): StudentReader =
        readers.firstOrNull { it.supports(mimeType, fileName) }
            ?: throw IllegalArgumentException("Format non supporté pour '$fileName' (mime=$mimeType)")
}